### PR TITLE
Improve perfomance by removing search for next node and disabling print statements

### PR DESCRIPTION
**Pull request by dclaganiere**
Removed search for next node to visit.
Added flag for debug print statements.

### CODE REVIEW

**Comment by Savestate2A03** [comment]
as mentioned in #1, i'm planning on implementing weighted distances so we don't want to get rid of search. also do you think the print statements use that much time? if so i can remove them but i really like to see progress of what i'm looking for.

**Comment by dclaganiere** [comment]
Yeah, the print statements are a major overhead at the moment and are only useful for debugging, as this thing should take <5s to run.

**Comment by Savestate2A03** [comment]
great to know, thanks for the insight

**Comment by Savestate2A03** [comment]
The code should be modified to where the prints are sparse enough now to not need a debug flag option

**Pull request closed without merging**
