### PR TITLE
Speed it up a lot by printing less and using a heap instead

### PR DESCRIPTION
**Pull request by Pwootage**
I am curious what the longest possible transition from one angle to another is, so I need to do some optimizations. This one is pretty easy to use upstream, if you'd like it :)

### CODE REVIEW

**Comment by dclaganiere** [comment]
This removes the O(n) overhead for searching for the next node, but we can do better; while inserts into a heap are O(1), deletes/pops are still O(log*n).

The canonical algorithm here for this type of problem is a Breadth-First Search or BFS:
https://en.wikipedia.org/wiki/Breadth-first_search

The data structure you want here is a queue, which can be implemented using a list in python (see my PR)

**Comment by Savestate2A03** [comment]
I just implemented weighted distances in longer ESS turns, so I don't know if this should be merged. I'm going to push the changes tomorrow and some general cleanup and you can make changes as you see fit. 

Appreciate it thus far!

**Comment by dclaganiere** [comment]
If you're doing weighted distances, then yes, a heap would be the best approach to find the next node to visit.

**Comment by Savestate2A03** [comment]
works beautifully, thank you so much! the speedup is incredible!

**Comment by Savestate2A03** [comment]
gonna see if I can have this merge instead of just close, whoops.

**Comment by Savestate2A03** [comment]
Can you rebase and undo those merges from this repo then open a pull request again?

**Comment by Savestate2A03** [comment]
I've got the code still made and ready but wanted to make it look like it got merged properly

**Comment by Pwootage** [comment]
Looks like it's showing up as merged, so that should be good

**Pull request merged**
